//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdConoceAColombiaEntities : DbContext
    {
        public bdConoceAColombiaEntities()
            : base("name=bdConoceAColombiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbArquitectura> tbArquitectura { get; set; }
        public virtual DbSet<tbArtistas> tbArtistas { get; set; }
        public virtual DbSet<tbCiudadesPrincipales> tbCiudadesPrincipales { get; set; }
        public virtual DbSet<tbDepartamento> tbDepartamento { get; set; }
        public virtual DbSet<tbDeportes> tbDeportes { get; set; }
        public virtual DbSet<tbGastronomia> tbGastronomia { get; set; }
        public virtual DbSet<tbTipodeArquitectura> tbTipodeArquitectura { get; set; }
        public virtual DbSet<tbTipodeArtista> tbTipodeArtista { get; set; }
        public virtual DbSet<tbTipodeGastronomia> tbTipodeGastronomia { get; set; }
        public virtual DbSet<tbTipoUsuario> tbTipoUsuario { get; set; }
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }
        public virtual DbSet<tbMusica> tbMusica { get; set; }
    }
}
