//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbArquitectura
    {
        public long arquCodigo { get; set; }
        public Nullable<long> arquDepartamento { get; set; }
        public string arquNombre { get; set; }
        public string arquCiudad { get; set; }
        public string arquLatitud { get; set; }
        public string arquLongitud { get; set; }
        public long arquTipo { get; set; }
    
        public virtual tbDepartamento tbDepartamento { get; set; }
        public virtual tbTipodeArquitectura tbTipodeArquitectura { get; set; }
    }
}
