//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbArtistas
    {
        public long artiCodigo { get; set; }
        public string artiNombre { get; set; }
        public long artiGenero { get; set; }
        public string artiCiudad { get; set; }
        public string artiLatitud { get; set; }
        public string artiLongitud { get; set; }
        public long artiDepartamento { get; set; }
        public string artiDescripcion { get; set; }
        public Nullable<System.DateTime> artiFechaNacimiento { get; set; }
    
        public virtual tbDepartamento tbDepartamento { get; set; }
        public virtual tbTipodeArtista tbTipodeArtista { get; set; }
    }
}
