//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCiudadesPrincipales
    {
        public long ciprCodigo { get; set; }
        public string ciprNombre { get; set; }
        public string ciprReseña { get; set; }
        public string ciprLatitud { get; set; }
        public string ciprLongitud { get; set; }
        public Nullable<long> ciprDepartamento { get; set; }
    
        public virtual tbDepartamento tbDepartamento { get; set; }
    }
}
