//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCulturas
    {
        public long cultCodigo { get; set; }
        public string cultNombre { get; set; }
        public string cultDescripcion { get; set; }
        public string cultLatitud { get; set; }
        public string cultLongitud { get; set; }
        public long cultDepartamento { get; set; }
        public string cultFechaInicio { get; set; }
        public string cultFechaFinal { get; set; }
        public long cultTipo { get; set; }
    
        public virtual tbDepartamento tbDepartamento { get; set; }
        public virtual tbTipoCultura tbTipoCultura { get; set; }
    }
}
