//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDepartamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbDepartamento()
        {
            this.tbArquitectura = new HashSet<tbArquitectura>();
            this.tbArtistas = new HashSet<tbArtistas>();
            this.tbCiudadesPrincipales = new HashSet<tbCiudadesPrincipales>();
            this.tbGastronomia = new HashSet<tbGastronomia>();
            this.tbMusica = new HashSet<tbMusica>();
        }
    
        public long depaCodigo { get; set; }
        public string depaNombre { get; set; }
        public string depaCapital { get; set; }
        public string depaGobernador { get; set; }
        public string depaMunicipios { get; set; }
        public System.DateTime depaFundacion { get; set; }
        public string depaGentilicio { get; set; }
        public string depaPoblacion { get; set; }
        public string depaSuperficie { get; set; }
        public string depaDemografia { get; set; }
        public string depaLatitud { get; set; }
        public string depaLongitud { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbArquitectura> tbArquitectura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbArtistas> tbArtistas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCiudadesPrincipales> tbCiudadesPrincipales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbGastronomia> tbGastronomia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMusica> tbMusica { get; set; }
    }
}
