//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDeportista
    {
        public long depoCodigo { get; set; }
        public string depoNombre { get; set; }
        public string depoDescripcion { get; set; }
        public long depoTipo { get; set; }
        public string depoCiudad { get; set; }
        public string depoLatitud { get; set; }
        public string depoLongitud { get; set; }
        public long depoDepartamento { get; set; }
        public Nullable<System.DateTime> depoFechaNacimiento { get; set; }
        public string depoImagen { get; set; }
    
        public virtual tbDepartamento tbDepartamento { get; set; }
        public virtual tbTipoDeportista tbTipoDeportista { get; set; }
    }
}
