//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDificultadJuego
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbDificultadJuego()
        {
            this.tbPreguntasJuego = new HashSet<tbPreguntasJuego>();
        }
    
        public long dijuCodigo { get; set; }
        public string dijuDescripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPreguntasJuego> tbPreguntasJuego { get; set; }
    }
}
