//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEquipos
    {
        public long equiCodigo { get; set; }
        public string equiNombre { get; set; }
        public string equiDescripcion { get; set; }
        public string equiPresidente { get; set; }
        public Nullable<System.DateTime> equiFundacion { get; set; }
        public string equiCiudad { get; set; }
        public Nullable<long> equiDeporte { get; set; }
        public Nullable<long> equiDepartamento { get; set; }
        public string equiLatitud { get; set; }
        public string equiLongitud { get; set; }
    
        public virtual tbDepartamento tbDepartamento { get; set; }
        public virtual tbDepartamento tbDepartamento1 { get; set; }
        public virtual tbDeportes tbDeportes { get; set; }
        public virtual tbDeportes tbDeportes1 { get; set; }
    }
}
