//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEstadios
    {
        public long estaCodigo { get; set; }
        public string estaNombre { get; set; }
        public string estaDescripcion { get; set; }
        public string estaFundacion { get; set; }
        public string estaCapacidad { get; set; }
        public string estaCiudad { get; set; }
        public string estaLatitud { get; set; }
        public string estaLongitud { get; set; }
        public long estaDepartamento { get; set; }
        public long estaDeporte { get; set; }
        public string estaImagen { get; set; }
    
        public virtual tbDepartamento tbDepartamento { get; set; }
        public virtual tbDeportes tbDeportes { get; set; }
    }
}
