//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFaunaxDepartamento
    {
        public long fxdCodigo { get; set; }
        public string fxdDescripcion { get; set; }
        public long fxdFauna { get; set; }
        public long fxdDepartamento { get; set; }
        public string fxdLatitud { get; set; }
        public string fxdLongitud { get; set; }
    
        public virtual tbDepartamento tbDepartamento { get; set; }
        public virtual tbFauna tbFauna { get; set; }
    }
}
