//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFauna
    {
        public long faunCodigo { get; set; }
        public string faunNombre { get; set; }
        public string faunDescripcion { get; set; }
        public long faunTipo { get; set; }
        public string faunLatitud { get; set; }
        public string faunLongitud { get; set; }
    
        public virtual tbTipoFauna tbTipoFauna { get; set; }
    }
}
