//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFlora
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbFlora()
        {
            this.tbFloraxDepartamento = new HashSet<tbFloraxDepartamento>();
        }
    
        public long florCodigo { get; set; }
        public string florNomCientifico { get; set; }
        public string florNomComun { get; set; }
        public string florDescripcion { get; set; }
        public string florAbundancia { get; set; }
        public string florPeriodoFloracion { get; set; }
        public long florTipo { get; set; }
    
        public virtual tbTipoFlora tbTipoFlora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFloraxDepartamento> tbFloraxDepartamento { get; set; }
    }
}
