//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFloraxDepartamento
    {
        public long foxdCodigo { get; set; }
        public long foxdFlora { get; set; }
        public long foxdDepartamento { get; set; }
        public string foxdLatitud { get; set; }
        public string foxdLongitud { get; set; }
    
        public virtual tbDepartamento tbDepartamento { get; set; }
        public virtual tbFlora tbFlora { get; set; }
    }
}
