//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbGastronomia
    {
        public long gastCodigo { get; set; }
        public string gastNombre { get; set; }
        public string gastDescripcion { get; set; }
        public string gastCiudad { get; set; }
        public string gastLatitud { get; set; }
        public string gastLongitud { get; set; }
        public Nullable<long> gastDepartamento { get; set; }
        public Nullable<long> gastTipo { get; set; }
        public string gastImagen { get; set; }
    
        public virtual tbDepartamento tbDepartamento { get; set; }
        public virtual tbTipodeGastronomia tbTipodeGastronomia { get; set; }
    }
}
