//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHistoria
    {
        public long histCodigo { get; set; }
        public string histDescripcion { get; set; }
        public Nullable<long> histTipo { get; set; }
        public Nullable<System.DateTime> histFechaInicio { get; set; }
        public Nullable<System.DateTime> histFechaFin { get; set; }
        public Nullable<long> histDepartamento { get; set; }
        public string histLatitud { get; set; }
        public string histLongitud { get; set; }
        public string histNombre { get; set; }
    
        public virtual tbDepartamento tbDepartamento { get; set; }
        public virtual tbTipodeHistoria tbTipodeHistoria { get; set; }
    }
}
