//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHistoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbHistoria()
        {
            this.tbPersonajesxHistoria = new HashSet<tbPersonajesxHistoria>();
        }
    
        public long histCodigo { get; set; }
        public string histDescripcion { get; set; }
        public Nullable<System.DateTime> histFechaInicio { get; set; }
        public Nullable<System.DateTime> histFechaFin { get; set; }
        public Nullable<long> histDepartamento { get; set; }
        public string histLatitud { get; set; }
        public string histLongitud { get; set; }
        public string histNombre { get; set; }
        public long histPeriodo { get; set; }
        public string histImagen { get; set; }
    
        public virtual tbDepartamento tbDepartamento { get; set; }
        public virtual tbPeriodoHistoria tbPeriodoHistoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPersonajesxHistoria> tbPersonajesxHistoria { get; set; }
    }
}
