//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLugares
    {
        public long lugaCodigo { get; set; }
        public string lugaNombre { get; set; }
        public string lugaDescripcion { get; set; }
        public string lugaCiudad { get; set; }
        public string lugaFundacion { get; set; }
        public string lugaDireccion { get; set; }
        public string lugaLatitud { get; set; }
        public string lugaLongitud { get; set; }
        public long lugaDepartamento { get; set; }
        public long lugaTipo { get; set; }
        public string lugaImagen { get; set; }
    
        public virtual tbDepartamento tbDepartamento { get; set; }
        public virtual tbTipoLugares tbTipoLugares { get; set; }
    }
}
