//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMusica
    {
        public long musiCodigo { get; set; }
        public string musiNombre { get; set; }
        public string musiDescripcion { get; set; }
        public Nullable<long> musiDepartamento { get; set; }
        public string musiLatitud { get; set; }
        public string musiLongitud { get; set; }
        public string musiImagen { get; set; }
    
        public virtual tbDepartamento tbDepartamento { get; set; }
    }
}
