//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPersonajesxHistoria
    {
        public Nullable<long> pxhPersonaje { get; set; }
        public Nullable<long> pxhHistoria { get; set; }
        public long pxhCodigo { get; set; }
    
        public virtual tbHistoria tbHistoria { get; set; }
        public virtual tbPersonajesHistoricos tbPersonajesHistoricos { get; set; }
    }
}
