//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPersonajesHistoricos
    {
        public long pehiCodigo { get; set; }
        public string pehiNombre { get; set; }
        public Nullable<System.DateTime> pehiNacimiento { get; set; }
        public string pehiCiudad { get; set; }
        public string pehiDescripcion { get; set; }
        public string pehiLatitud { get; set; }
        public string pehiLongitud { get; set; }
    }
}
