//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPersonajeAprendizaje
    {
        public long apreCodigo { get; set; }
        public string apreNombre { get; set; }
        public string apreDescripcion { get; set; }
        public long apreTipo { get; set; }
        public string apreCiudad { get; set; }
        public string apreLatitud { get; set; }
        public string apreLongitud { get; set; }
        public long apreDepartamento { get; set; }
        public Nullable<System.DateTime> apreFechaNacimiento { get; set; }
    
        public virtual tbDepartamento tbDepartamento { get; set; }
        public virtual tbTipoPersonajeAprendizaje tbTipoPersonajeAprendizaje { get; set; }
    }
}
