//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPolitico
    {
        public long poliCodigo { get; set; }
        public string poliNombre { get; set; }
        public string poliDescripcion { get; set; }
        public long poliTipo { get; set; }
        public string poliCiudad { get; set; }
        public string poliLatitud { get; set; }
        public string poliLongitud { get; set; }
        public long poliDepartamento { get; set; }
        public Nullable<System.DateTime> poliFechaNacimiento { get; set; }
    
        public virtual tbTipoPolitico tbTipoPolitico { get; set; }
    }
}
