//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPreguntasJuego
    {
        public long prjuCodigo { get; set; }
        public string prjuPregunta { get; set; }
        public string prjuRespuestaCorrecta { get; set; }
        public string prjuRespuestaIncorrectaUno { get; set; }
        public string prjuRespuestaIncorrectaDos { get; set; }
        public string prjuRespuestaIncorrectaTres { get; set; }
        public string prjuRespuestaIncorrectaCuatro { get; set; }
        public string prjuRespuestaIncorrectaCinco { get; set; }
        public long prjuTematica { get; set; }
        public long prjuTipoJuego { get; set; }
        public long prjuDificultad { get; set; }
    
        public virtual tbDificultadJuego tbDificultadJuego { get; set; }
        public virtual tbTematicaJuego tbTematicaJuego { get; set; }
        public virtual tbTipoJuego tbTipoJuego { get; set; }
    }
}
