//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPuntajePorPersona
    {
        public long pupeCodigo { get; set; }
        public string pupeNombreCompleto { get; set; }
        public Nullable<decimal> pupePuntaje { get; set; }
        public string pupeTipoJuego { get; set; }
        public string pupeDificultad { get; set; }
    }
}
