//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTipoPersonajeAprendizaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbTipoPersonajeAprendizaje()
        {
            this.tbPersonajeAprendizaje = new HashSet<tbPersonajeAprendizaje>();
        }
    
        public long tiapCodigo { get; set; }
        public string tiapDescripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPersonajeAprendizaje> tbPersonajeAprendizaje { get; set; }
    }
}
