//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConoceAColombia.logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuarios
    {
        public int usuaCodigo { get; set; }
        public string usuaNombre { get; set; }
        public string usuaApellido { get; set; }
        public string usuaCorreo { get; set; }
        public string usuaPassword { get; set; }
        public Nullable<int> usuaPuntuacionMaxima { get; set; }
        public int usuaTipo { get; set; }
        public string usuaImagen { get; set; }
    
        public virtual tbTipoUsuario tbTipoUsuario { get; set; }
    }
}
